'use client'

import { PageTitle } from '@/app/components/pagetitle';
import {notFound, useSearchParams} from "next/navigation";
import {useEffect, useState} from "react";

import * as Carmentis from '@/carmentis-nodejs-sdk';
import {GetMasterBlockResponse} from "@/app/interfaces/getMasterBlockResponse";
import {Formatters} from "@/app/utils/formatters";
import TableMicroBlocks from "@/app/components/tableMicroBlocks";

export default function MasterBlockExplorer() {

    // obtains the searched master block id from query parameter
    // or fails if not provided.
    // Note: the search params can be null.
    const searchParams = useSearchParams();
    let rawBlockId = null;
    if ( searchParams ) {
        rawBlockId = searchParams.get('blockId');
    }
    if ( rawBlockId === null ) {
        notFound();
    }

    // we parse the block id
    const blockId = parseInt(rawBlockId);
    const [response, setResponse] = useState<GetMasterBlockResponse>();


    useEffect(() => {
        Carmentis.registerNodeEndpoint("https://node.testapps.carmentis.io")
        Carmentis.getMasterBlock(blockId).then((response: GetMasterBlockResponse) => {
            console.log(response)
            setResponse(response)
        });
    }, [blockId]);

    return (
        <>
            <PageTitle title={`Master Block Explorer - Block ${blockId}`}/>

            <section className="section profile">
                <div className="row">
                    <div className="col-xl-0">
                        <div className="card">
                            <div className="card-body pt-3">
                                <ul className="nav nav-tabs nav-tabs-bordered" role="tablist">
                                    <li className="nav-item" role="presentation">
                                        <button className="nav-link active" data-bs-toggle="tab"
                                                data-bs-target="#block-overview" aria-selected="true" role="tab">Summary
                                        </button>
                                    </li>
                                    <li className="nav-item" role="presentation">
                                        <button className="nav-link" data-bs-toggle="tab" data-bs-target="#block-hashes"
                                                aria-selected="false" tabIndex={-1} role="tab">Hashes
                                        </button>
                                    </li>
                                </ul>
                                <div className="tab-content pt-2">
                                    <div className="tab-pane fade show active profile-overview" id="block-overview"
                                         role="tabpanel"><h5 className="card-title">Block Summary</h5>
                                        <div className="row">
                                            <div className="col-lg-3 col-md-4 label">Date</div>
                                            <div id="ind0-0" className="col-lg-9 col-md-8">
                                                {
                                                    response && Formatters.formatTimestampToLocalDate(response.header.ts)
                                                }
                                            </div>
                                        </div>
                                        <div className="row">
                                            <div className="col-lg-3 col-md-4 label">Status</div>
                                            <div id="ind0-1" className="col-lg-9 col-md-8">

                                            </div>
                                        </div>
                                        <div className="row">
                                            <div className="col-lg-3 col-md-4 label">Generated by</div>
                                            <div id="ind0-2"
                                                 className="col-lg-9 col-md-8">
                                                {response && Formatters.formatHash(response.header.nodeId)}
                                            </div>
                                        </div>
                                        <div className="row">
                                            <div className="col-lg-3 col-md-4 label">Number of micro blocks</div>
                                            <div id="ind0-3" className="col-lg-9 col-md-8">
                                                {response && response.microBlock.length}
                                            </div>
                                        </div>
                                    </div>
                                    <div className="tab-pane fade profile-overview" id="block-hashes" role="tabpanel">
                                        <h5 className="card-title">Block Hashes</h5>
                                        <div className="row">
                                            <div className="col-lg-3 col-md-4 label">Block hash</div>
                                            <div id="ind1-0" className="col-lg-9 col-md-8 mono">-</div>
                                        </div>
                                        <div className="row">
                                            <div className="col-lg-3 col-md-4 label">Previous block hash</div>
                                            <div id="ind1-1"
                                                 className="col-lg-9 col-md-8 mono">
                                                {response && Formatters.formatHash(response.header.previousHash)}
                                            </div>
                                        </div>
                                        <div className="row">
                                            <div className="col-lg-3 col-md-4 label">Root hash of Merkle tree</div>
                                            <div id="ind1-2"
                                                 className="col-lg-9 col-md-8 mono">
                                                {response && Formatters.formatHash(response.header.merkleRootHash)}
                                            </div>
                                        </div>
                                        <div className="row">
                                            <div className="col-lg-3 col-md-4 label">Root hash of radix tree</div>
                                            <div id="ind1-3"
                                                 className="col-lg-9 col-md-8 mono">
                                                {response && Formatters.formatHash(response.header.radixRootHash)}
                                            </div>
                                        </div>
                                    </div>
                                    <div className="tab-pane fade profile-overview" id="block-signatures"
                                         role="tabpanel"><h5 className="card-title">Block Signatures</h5>
                                        <div className="row">
                                            <div className="col-lg-3 col-md-4 label">Node signature</div>
                                            <div id="ind2-0" className="col-lg-9 col-md-8 mono">-</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="card">
                            <div className="card-body"><h5 className="card-title">Micro Blocks</h5>
                                {
                                    response?.microBlock &&
                                    <TableMicroBlocks blocks={response.microBlock}/>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    );
}